title: Sepehr Salemriad
logo: "/images/Sepehr_Salemirad.jpg?raw=true"
description: >
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="www.linkedin.com/in/sepehrsalemirad">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
