title: <p align="center"> Sepehr Salemirad </p>
logo: "/images/Sepehr_Salemirad.png?raw=true"
description:
  <p align="center">
  <a href="https://linkedin.com/in/sepehrsalemirad">LinkedIn</a> |
  <a href="https://github.com/SepehrRad">GitHub</a>
  </p>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0
