title: Sepehr Salemriad
logo: "/images/Sepehr_Salemirad_circle.png?raw=true"
description: >
  I am an Information Systems graduate student (M.Sc.) with a passion for machine learning, cloud-native web development, and quantitative finance.
  <br><br>
  I am currently working as an Enterprise Software Engineer at innovas GmbH (.msg group) with a focus on cloud-native web development using Spring & Angular.
  <br><br>
  <a href="www.linkedin.com/in/sepehrsalemirad">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
